// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelsConfig } from "./ModelsConfig";

/**
 * The full configuration document.
 */
export type AppConfig = { 
/**
 * Schema version of this document.
 */
version: number, 
/**
 * Model storage + budget.
 */
models: ModelsConfig, };
