// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoggingConfig } from "./LoggingConfig";
import type { ModelsConfig } from "./ModelsConfig";
import type { ResourcesConfig } from "./ResourcesConfig";

/**
 * The full configuration document.
 */
export type AppConfig = { 
/**
 * Schema version of this document.
 */
version: number, 
/**
 * Model storage + budget.
 */
models: ModelsConfig, 
/**
 * Logging.
 */
logging: LoggingConfig, 
/**
 * Resource manager tuning (schema v4).
 */
resources: ResourcesConfig, };
