// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageConfig } from "./ImageConfig";
import type { LoggingConfig } from "./LoggingConfig";
import type { ModelsConfig } from "./ModelsConfig";
import type { ResourcesConfig } from "./ResourcesConfig";
import type { RuntimesConfig } from "./RuntimesConfig";
import type { VoiceConfig } from "./VoiceConfig";
import type { WorkersConfig } from "./WorkersConfig";

/**
 * The full configuration document.
 */
export type AppConfig = { 
/**
 * Schema version of this document.
 */
version: number, 
/**
 * Model storage + budget.
 */
models: ModelsConfig, 
/**
 * Logging.
 */
logging: LoggingConfig, 
/**
 * Resource manager tuning (schema v4).
 */
resources: ResourcesConfig, 
/**
 * Where supervised runtime binaries live (schema v5).
 */
runtimes: RuntimesConfig, 
/**
 * Python worker layout (schema v6, ADR-0018).
 */
workers: WorkersConfig, 
/**
 * Voice input settings (schema v6, ADR-0005).
 */
voice: VoiceConfig, 
/**
 * Image generation settings (schema v9, ADR-0006).
 */
image: ImageConfig, };
