// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error returned across the IPC boundary. Serialized as
 * `{ "kind": "...", "message": "..." }` for the frontend to switch on.
 */
export type AppError = { "kind": "NotFound", "message": string } | { "kind": "Validation", "message": string } | { "kind": "Backend", "message": string } | { "kind": "Cancelled" } | { "kind": "Internal" };
