// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for [`app_ready`] — the startup handshake.
 */
export type AppReady = { 
/**
 * Core crate version.
 */
version: string, };
