// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Content address of a stored blob: the lowercase hex SHA-256 of the bytes
 * (`blobs/<sha256[0:2]>/<sha256>`).
 */
export type AssetId = string;
