// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The build that produced this binary.
 */
export type BuildInfo = { 
/**
 * Crate version (`Cargo.toml`).
 */
version: string, 
/**
 * Short git SHA at build time (empty if unavailable).
 */
git_sha: string, 
/**
 * `debug` or `release`.
 */
profile: string, };
