// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskId } from "./TaskId";

/**
 * Request to cancel a running or queued task. Idempotent: cancelling an
 * already-terminal task is a no-op, not an error.
 */
export type CancelRequest = { 
/**
 * The task to cancel.
 */
task_id: TaskId, };
