// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";
import type { ModelId } from "./ModelId";

/**
 * Request body for [`chat_send`].
 */
export type ChatSendRequest = { 
/**
 * Which conversation.
 */
conversation_id: ConversationId, 
/**
 * Which loaded model to generate with.
 */
model_id: ModelId, 
/**
 * The user's message.
 */
text: string, };
