// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A settable configuration key. The set is small and explicit; it grows
 * additively as phases add settings.
 */
export type ConfigKey = "ModelsDir" | "ModelsBudgetGb" | "ModelsMinFreeGb" | "LoggingLevel" | "VramSafetyMarginMb" | "RuntimesDir" | "WorkersDir" | "WorkersPython" | "VoiceInputDevice" | "VoiceOutputDevice";
