// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigKey } from "./ConfigKey";

/**
 * Request body for [`crate::ipc::commands::config_set`].
 */
export type ConfigSet = { 
/**
 * Which key to change.
 */
key: ConfigKey, 
/**
 * The new value, as a string (parsed per key).
 */
value: string, 
/**
 * `true` writes it to the config file; `false` sets a session-only override.
 */
persist: boolean, };
