// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigKey } from "./ConfigKey";

/**
 * One row of [`ConfigManager::keys`].
 */
export type ConfigKeyInfo = { 
/**
 * The key.
 */
key: ConfigKey, 
/**
 * Dotted path (`models.dir`).
 */
dotted: string, 
/**
 * A hint at the expected value form (`path`, `integer`).
 */
value_type: string, 
/**
 * Current effective value, stringified.
 */
current: string, };
