// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which tab / entity a conversation is bound to.
 */
export type ConversationKind = "Persona" | "Character";
