// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";
import type { ConversationKind } from "./ConversationKind";

/**
 * A conversation header (messages are fetched separately).
 */
export type Conversation = { 
/**
 * Stable identifier.
 */
id: ConversationId, 
/**
 * Persona vs Character.
 */
kind: ConversationKind, 
/**
 * Display title; may be absent until the first turn names it.
 */
title: string | null, 
/**
 * RFC-3339 creation timestamp.
 */
created_at: string, 
/**
 * RFC-3339 timestamp of the most recent activity.
 */
updated_at: string, };
