// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a conversation (Persona tab or Character tab).
 */
export type ConversationId = string;
