// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversation metadata — **never** content.
 */
export type ConversationMeta = { 
/**
 * Conversation id.
 */
id: string, 
/**
 * `Persona` / `Character`.
 */
kind: string, 
/**
 * Number of messages.
 */
messages: number, 
/**
 * Last-updated timestamp (RFC-3339).
 */
updated_at: string, };
