// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildInfo } from "./BuildInfo";
import type { ConversationMeta } from "./ConversationMeta";
import type { HostInfo } from "./HostInfo";

/**
 * The full snapshot.
 */
export type DiagSnapshot = { 
/**
 * When this snapshot was taken (RFC-3339).
 */
taken_at: string, 
/**
 * Build provenance.
 */
build: BuildInfo, 
/**
 * Effective config, redacted (carries no secret today; the guard stays).
 */
config: unknown, 
/**
 * Registered models (paths + metadata, no weights).
 */
models: unknown, 
/**
 * Resource-manager snapshot (GPU / RAM / reservations).
 */
resources: unknown, 
/**
 * Per-model lifecycle status.
 */
lifecycle: unknown, 
/**
 * Conversation metadata (no content).
 */
conversations: Array<ConversationMeta>, 
/**
 * Recent (already-redacted) log lines.
 */
recent_logs: Array<string>, 
/**
 * Host facts.
 */
host: HostInfo, };
