// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies an in-progress or completed model download (Phase 12).
 */
export type DownloadId = string;
