// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for [`download_start`].
 */
export type DownloadRequest = { 
/**
 * `owner/name`.
 */
repo: string, 
/**
 * File within the repo.
 */
filename: string, 
/**
 * Size in bytes from the file listing (for the budget check).
 */
size: bigint | null, 
/**
 * SHA-256 from the file listing (for verification).
 */
sha256: string | null, };
