// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a download. `Complete` and `Failed` are terminal (a `Failed`
 * download can be retried, which creates a fresh row).
 */
export type DownloadState = "Queued" | "Downloading" | "Paused" | "Verifying" | "Complete" | "Failed";
