// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadId } from "./DownloadId";
import type { DownloadState } from "./DownloadState";
import type { ModelKind } from "./ModelKind";

/**
 * A download as the picker sees it.
 */
export type DownloadInfo = { 
/**
 * Stable id.
 */
id: DownloadId, 
/**
 * Source repo.
 */
repo: string, 
/**
 * File within the repo.
 */
filename: string, 
/**
 * What kind of model this file is.
 */
kind: ModelKind, 
/**
 * Current state.
 */
state: DownloadState, 
/**
 * Total size in bytes, once known.
 */
total_bytes: bigint | null, 
/**
 * Bytes transferred so far.
 */
downloaded_bytes: bigint, 
/**
 * Last error message, for a `Failed` download.
 */
error: string | null, };
