// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadState } from "./DownloadState";

/**
 * A progress tick, delivered over the per-download Tauri Channel.
 */
export type DownloadProgress = { 
/**
 * Bytes transferred so far.
 */
downloaded_bytes: bigint, 
/**
 * Total size, once known.
 */
total_bytes: bigint | null, 
/**
 * Terminal state reached, if any (the last tick of a finished download).
 */
done: DownloadState | null, };
