// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { TaskId } from "./TaskId";

/**
 * An [`AppError`] plus optional task correlation. Used where the `kind` alone
 * is not enough to route the failure (e.g. one of several concurrent tasks
 * failed).
 */
export type ErrorEnvelope = { 
/**
 * The underlying error.
 */
error: AppError, 
/**
 * The task this failure belongs to, when there is one.
 */
task_id: TaskId | null, };
