// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontendLogLevel } from "./FrontendLogLevel";

/**
 * A log line forwarded from the frontend. The frontend never writes logs
 * directly — it routes them here so everything lands in one structured stream.
 */
export type FrontendLog = { level: FrontendLogLevel, target: string, message: string, };
