// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Log levels the frontend may forward. Mirrors `tracing::Level`.
 */
export type FrontendLogLevel = "error" | "warn" | "info" | "debug" | "trace";
