// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetId } from "./AssetId";
import type { GeneratedImageId } from "./GeneratedImageId";

/**
 * One generated image with its provenance — the `generated_image` row as the
 * frontend sees it.
 */
export type GeneratedImageRow = { 
/**
 * Stable id.
 */
id: GeneratedImageId, 
/**
 * Content address of the PNG bytes — resolve via `image_bytes`.
 */
asset: AssetId, 
/**
 * The prompt used.
 */
prompt: string, 
/**
 * Image width in px.
 */
width: number, 
/**
 * Image height in px.
 */
height: number, 
/**
 * The seed used for this image.
 */
seed: bigint, 
/**
 * LoRA display name, or `None` for the base model.
 */
lora: string | null, 
/**
 * RFC-3339 creation timestamp.
 */
created_at: string, };
