// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { SamplingParams } from "./SamplingParams";
import type { TaskId } from "./TaskId";

/**
 * A request to generate text. The `prompt` is already fully assembled by the
 * context builder (Phase 20) — this contract does not know about personas.
 */
export type GenerationRequest = { 
/**
 * Correlates the request with its [`crate::contracts::task::TaskStatus`] and
 * its cancellation.
 */
task_id: TaskId, 
/**
 * Which model to run.
 */
model: ModelId, 
/**
 * The fully-rendered prompt.
 */
prompt: string, 
/**
 * Sampling configuration.
 */
params: SamplingParams, };
