// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationHandle } from "./GenerationHandle";

/**
 * The conversation engine's streaming state. `generating` is `Some` while a
 * reply is being produced, `None` at rest.
 */
export type GenerationState = { 
/**
 * The running generation, if any.
 */
generating: GenerationHandle | null, };
