// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one generated image and its provenance row (Phase 22).
 */
export type GeneratedImageId = string;
