// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { StopReason } from "./StopReason";

/**
 * One frame of a streaming generation. Adjacently tagged:
 * `{ "type": "TokenDelta", "data": { ... } }`.
 */
export type GenerationEvent = { "type": "TokenDelta", "data": { 
/**
 * 0-based index of this delta within the stream.
 */
index: number, 
/**
 * The text of this chunk (may be a partial word).
 */
text: string, } } | { "type": "Done", "data": { 
/**
 * Why it stopped.
 */
stop_reason: StopReason, 
/**
 * Total tokens generated.
 */
tokens: number, } } | { "type": "Error", "data": { 
/**
 * The failure.
 */
error: AppError, } } | { "type": "Cancelled" };
