// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";
import type { TaskId } from "./TaskId";

/**
 * The running generation, when the engine has one (Phase 17).
 */
export type GenerationHandle = { 
/**
 * The generation's task id — pass it to `chat_cancel`.
 */
task_id: TaskId, 
/**
 * The conversation the reply is being generated for.
 */
conversation_id: ConversationId, };
