// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { StopReason } from "./StopReason";

/**
 * Provenance for an assistant message produced by a generation.
 */
export type GenerationMeta = { 
/**
 * Model that produced the message.
 */
model: ModelId, 
/**
 * Why generation stopped.
 */
stop_reason: StopReason, 
/**
 * Tokens generated.
 */
tokens: number, 
/**
 * Wall-clock generation time in milliseconds.
 */
duration_ms: bigint, };
