// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A measured GPU memory reading (whole-GPU — per-process attribution is
 * unavailable on this driver, ADR-0007). All values in MB.
 */
export type GpuMemory = { 
/**
 * Total VRAM on the device.
 */
total_mb: bigint, 
/**
 * VRAM in use across the whole system.
 */
used_mb: bigint, 
/**
 * VRAM currently free.
 */
free_mb: bigint, };
