// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `.gguf` file in a repo, with header metadata when it could be read.
 */
export type HfGgufFile = { 
/**
 * Path within the repo.
 */
filename: string, 
/**
 * Size in bytes, when the API reports it.
 */
size: bigint | null, 
/**
 * Quant label from the GGUF header (`Q4_K_M`, …).
 */
quant: string | null, 
/**
 * Context length from the GGUF header.
 */
context_length: number | null, 
/**
 * SHA-256 (HF LFS hash), when available — used for integrity verification.
 */
sha256: string | null, };
