// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One model from an HF search.
 */
export type HfModelSummary = { 
/**
 * `owner/name`.
 */
repo: string, 
/**
 * Download count, when the API reports it.
 */
downloads: bigint | null, 
/**
 * Like count, when the API reports it.
 */
likes: bigint | null, 
/**
 * RFC-3339 last-modified, when the API reports it.
 */
updated: string | null, };
