// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read-only host facts.
 */
export type HostInfo = { 
/**
 * OS description.
 */
os: string, 
/**
 * `nvidia-smi` one-liner, if the tool is present.
 */
nvidia_smi: string | null, 
/**
 * Where the rotating log files live.
 */
log_dir: string | null, };
