// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which stage of the (currently manual — Phase 23 automates it) evict → load →
 * generate → restore sequence a job is in. Drives the UI's "waiting…" copy.
 */
export type ImagePhase = "Evicting" | "Loading" | "Generating" | "Restoring";
