// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImagePhase } from "./ImagePhase";

/**
 * Progress of one image generation.
 */
export type ImageProgress = { 
/**
 * Current stage.
 */
phase: ImagePhase, 
/**
 * Completed denoising steps for the current image (0 outside `Generating`).
 */
step: number, 
/**
 * Total steps for the current image.
 */
total_steps: number, 
/**
 * 0-based index of the current image within the batch.
 */
image_index: number, 
/**
 * Batch size.
 */
batch_count: number, };
