// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a realism LoRA in the image-model LoRA registry (Phase 22,
 * ADR-0006).
 */
export type ImageLoraId = string;
