// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The parameter values a preset carries.
 */
export type ImagePresetParams = { 
/**
 * Image width in px.
 */
width: number, 
/**
 * Image height in px.
 */
height: number, 
/**
 * Denoising steps.
 */
steps: number, 
/**
 * `guidance_scale`.
 */
guidance: number, };
