// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Image-generation settings (schema v9, ADR-0006). The dir overrides are
 * file-only (like the VAD thresholds); `null` resolves to a subdir of
 * `models.dir` at wiring time.
 */
export type ImageConfig = { 
/**
 * Directory holding the realism LoRA `*.safetensors`. `null` ⇒
 * `<models.dir>/image/loras`.
 */
loras_dir: string | null, 
/**
 * Directory holding the NF4 quant cache for Krea 2. `null` ⇒
 * `<models.dir>/image/quant_cache/krea2`.
 */
quant_cache_dir: string | null, 
/**
 * How long the image sidecar stays resident (~1.6 GB) after a generation
 * before it is unloaded. Seconds, `0..=3600`, default 300.
 */
idle_shutdown_s: bigint, };
