// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageLoraId } from "./ImageLoraId";

/**
 * A realism LoRA available to Krea 2, as the picker sees it (the file path
 * never crosses the wire).
 */
export type ImageLora = { 
/**
 * Registry id — put in a [`LoraSelection`].
 */
id: ImageLoraId, 
/**
 * Human-readable name.
 */
display_name: string, 
/**
 * Base model this LoRA is trained for (`"krea2"`).
 */
base_compat: string, 
/**
 * Suggested adapter weight.
 */
default_weight: number, 
/**
 * Free-form tags (`"realism"`, `"skin"`, `"nsfw"`).
 */
tags: Array<string>, };
