// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImagePresetId } from "./ImagePresetId";
import type { ImagePresetParams } from "./ImagePresetParams";

/**
 * A saved image-generation parameter set.
 */
export type ImagePreset = { 
/**
 * Stable id.
 */
id: ImagePresetId, 
/**
 * Unique name.
 */
name: string, 
/**
 * The parameters.
 */
params: ImagePresetParams, };
