// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a saved image-generation parameter preset (Phase 22).
 */
export type ImagePresetId = string;
