// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { GeneratedImageRow } from "./GeneratedImageRow";
import type { ImageProgress } from "./ImageProgress";

/**
 * One frame of a streaming image generation. Adjacently tagged:
 * `{ "type": "Progress", "data": { ... } }`.
 */
export type ImageEvent = { "type": "Progress", "data": ImageProgress } | { "type": "Done", "data": { 
/**
 * The generated images, in batch order.
 */
images: Array<GeneratedImageRow>, } } | { "type": "Error", "data": { 
/**
 * The failure.
 */
error: AppError, } } | { "type": "Cancelled" };
