// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoraSelection } from "./LoraSelection";

/**
 * A request to generate one or more images with Krea 2 Turbo.
 */
export type ImageRequest = { 
/**
 * The positive prompt (untrusted user text).
 */
prompt: string, 
/**
 * Optional negative prompt. Inert at `guidance_scale 0` (Turbo's default) —
 * carried so raising guidance is the only change needed to use it.
 */
negative: string | null, 
/**
 * Image width in px — a multiple of 16 within `512..=1664`.
 */
width: number, 
/**
 * Image height in px — a multiple of 16 within `512..=1664`.
 */
height: number, 
/**
 * Denoising steps; `None` = the model default (8).
 */
steps: number | null, 
/**
 * `guidance_scale`; `None` = the model default (0.0).
 */
guidance: number | null, 
/**
 * RNG seed; `None` = a fresh seed per request. Batch image `i` uses
 * `seed + i`.
 */
seed: bigint | null, 
/**
 * How many images to generate (`1..=8`).
 */
batch_count: number, 
/**
 * LoRA selection — 0 or 1 entry in v1.
 */
loras: Array<LoraSelection>, };
