// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable input device.
 */
export type InputDevice = { 
/**
 * Human-readable name; also the selection key persisted in config.
 */
name: string, 
/**
 * Whether this is the host's current default.
 */
is_default: boolean, };
