// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { ModelState } from "./ModelState";

/**
 * One row of the lifecycle manager's runtime view (Phase 14): a model it is
 * tracking, its [`ModelState`], and — once loaded — its measured VRAM.
 */
export type LifecycleStatus = { 
/**
 * The model.
 */
id: ModelId, 
/**
 * Its runtime state.
 */
state: ModelState, 
/**
 * Measured VRAM footprint in MB, when loaded and the backend reports it.
 */
vram_mb: number | null, 
/**
 * The last error string, when `state` is `Failed`.
 */
error: string | null, };
