// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Logging configuration (schema v2).
 */
export type LoggingConfig = { 
/**
 * A `tracing` filter directive (`info`, `warn`, `warn,localai=debug`, …).
 * The `LOCALAI_LOG` env var, when set, overrides this.
 */
level: string, };
