// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageLoraId } from "./ImageLoraId";

/**
 * One LoRA applied to a generation. v1 applies at most one (`loras[0]`); the
 * list is carried so multi-LoRA stacking is a non-breaking later add
 * (ADR-0006).
 */
export type LoraSelection = { 
/**
 * Registry id of the LoRA.
 */
id: ImageLoraId, 
/**
 * Adapter weight, `0.0..=1.0`.
 */
weight: number, };
