// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";
import type { MemoryId } from "./MemoryId";
import type { MemoryKind } from "./MemoryKind";

/**
 * One stored memory, as shown in the "view memories" list (FR-52).
 */
export type Memory = { 
/**
 * Stable id — pass to `memory_delete`.
 */
id: MemoryId, 
/**
 * Category.
 */
kind: MemoryKind, 
/**
 * The remembered text.
 */
content: string, 
/**
 * 1..5 — higher is kept longer and ranked ahead on a tie.
 */
importance: number, 
/**
 * The conversation this was extracted from, if it still exists.
 */
source_conversation_id: ConversationId | null, 
/**
 * RFC-3339 creation timestamp.
 */
created_at: string, };
