// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing a memory records. Kept small and fixed for v1.
 */
export type MemoryKind = "Fact" | "Preference" | "Event" | "Trait";
