// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetId } from "./AssetId";

/**
 * The body of a message. Adjacently tagged:
 * `{ "type": "Text", "data": { "text": "..." } }`.
 */
export type MessageContent = { "type": "Text", "data": { 
/**
 * The text body.
 */
text: string, } } | { "type": "Audio", "data": { 
/**
 * Content-addressed audio blob.
 */
asset: AssetId, 
/**
 * Transcript text, when transcription has completed.
 */
transcript: string | null, } } | { "type": "Image", "data": { 
/**
 * Content-addressed image blob.
 */
asset: AssetId, 
/**
 * Optional caption / prompt echo.
 */
caption: string | null, } };
