// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";
import type { GenerationMeta } from "./GenerationMeta";
import type { MessageContent } from "./MessageContent";
import type { MessageId } from "./MessageId";
import type { Role } from "./Role";

/**
 * One message in a conversation.
 */
export type Message = { 
/**
 * Stable identifier.
 */
id: MessageId, 
/**
 * The conversation this message belongs to.
 */
conversation_id: ConversationId, 
/**
 * Author.
 */
role: Role, 
/**
 * Body.
 */
content: MessageContent, 
/**
 * RFC-3339 creation timestamp.
 */
created_at: string, 
/**
 * Generation provenance, for assistant messages.
 */
generation: GenerationMeta | null, };
