// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The role a model plays in a pipeline.
 */
export type ModelKind = "Llm" | "Stt" | "Tts" | "Image" | "Embedder";
