// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelBackend } from "./ModelBackend";
import type { ModelCapabilities } from "./ModelCapabilities";
import type { ModelId } from "./ModelId";
import type { ModelKind } from "./ModelKind";
import type { Quant } from "./Quant";

/**
 * Static description of a registered model. Persistence + `ModelId` stability
 * are Phase 11; this is only the shared shape.
 */
export type ModelMetadata = { 
/**
 * Stable identifier.
 */
id: ModelId, 
/**
 * Human-facing name (from the model card / file).
 */
display_name: string, 
/**
 * Pipeline role.
 */
kind: ModelKind, 
/**
 * Executing runtime.
 */
backend: ModelBackend, 
/**
 * Quantization, if any.
 */
quant: Quant | null, 
/**
 * Declared capabilities.
 */
capabilities: ModelCapabilities, 
/**
 * Rough VRAM footprint in MB when loaded, when known (Phase 13 refines it).
 */
estimated_vram_mb: number | null, };
