// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where downloaded models live and how much disk they may use.
 */
export type ModelsConfig = { 
/**
 * Absolute directory for downloaded model files. Default: `<app_data>/models`.
 */
dir: string, 
/**
 * Maximum disk the model directory may occupy, in GB. Must be `>= 1`.
 */
budget_gb: number, 
/**
 * Disk headroom (GB) to keep free — a download that would leave less than
 * this is refused before it starts (schema v3). Must be `>= 1`.
 */
min_free_gb: number, };
