// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where downloaded models live and how much disk they may use.
 */
export type ModelsConfig = { 
/**
 * Absolute directory for downloaded model files. Default: `<app_data>/models`.
 */
dir: string, 
/**
 * Maximum disk the model directory may occupy, in GB. Must be `>= 1`.
 */
budget_gb: number, };
