// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a registered model. Stable across restarts and path changes
 * (Phase 11).
 */
export type ModelId = string;
