// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime state of a model in the lifecycle manager (Phase 14). Terminal only
 * in the sense that `Failed` needs an explicit recovery transition.
 */
export type ModelState = "Unloaded" | "Loading" | "Loaded" | "Busy" | "Failed" | "Unloading";
