// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which runtime executes a model, as an opaque identifier. Opaque on
 * purpose: logic switches on [`ModelKind`], not on the backend string.
 */
export type ModelBackend = string;
