// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a model can do. Minimal for Phase 7; extended additively as backends
 * land.
 */
export type ModelCapabilities = { 
/**
 * Whether the model can stream output incrementally.
 */
streaming: boolean, 
/**
 * Maximum context length in tokens, when it applies (LLM/embedder).
 */
context_tokens: number | null, };
