// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable output device.
 */
export type OutputDevice = { 
/**
 * Human-readable name; the selection key persisted in config.
 */
name: string, 
/**
 * Whether this is the host default.
 */
is_default: boolean, };
