// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The editable fields (create / update).
 */
export type PersonaDraft = { 
/**
 * Display name (required, non-blank).
 */
name: string, 
/**
 * One line — who they are.
 */
summary: string, 
/**
 * Personality traits.
 */
personality: string, 
/**
 * Tone of voice.
 */
tone: string, 
/**
 * Communication style.
 */
style: string, 
/**
 * Do / don't lines.
 */
guidance: Array<string>, };
