// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaId } from "./PersonaId";

/**
 * A stored persona.
 */
export type Persona = { 
/**
 * Stable id.
 */
id: PersonaId, 
/**
 * Display name; also used as "You are {name}." in the prompt.
 */
name: string, 
/**
 * One line — who they are.
 */
summary: string, 
/**
 * Personality traits.
 */
personality: string, 
/**
 * Tone of voice.
 */
tone: string, 
/**
 * Communication style.
 */
style: string, 
/**
 * Do / don't lines rendered as "Always: …".
 */
guidance: Array<string>, 
/**
 * RFC-3339.
 */
created_at: string, 
/**
 * RFC-3339.
 */
updated_at: string, };
