// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the persona made it into the prompt.
 */
export type PersonaInclusion = "Absent" | "Full" | "Truncated";
