// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for [`app_ping`].
 */
export type Pong = { 
/**
 * Echoes the request's nonce so the caller can correlate.
 */
nonce: string, 
/**
 * Core crate version.
 */
version: string, };
