// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provenance } from "./Provenance";

/**
 * The exact assembled prompt for the next generation on a conversation, plus
 * its [`Provenance`] — the FR-34 "show prompt" surface.
 */
export type PromptPreview = { 
/**
 * The full string the LLM adapter would receive.
 */
prompt: string, 
/**
 * What went into it (token budget, persona inclusion, history kept/dropped).
 */
provenance: Provenance, };
