// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonaInclusion } from "./PersonaInclusion";

/**
 * What went into the assembled prompt.
 */
export type Provenance = { 
/**
 * Estimated tokens in the whole prompt.
 */
total_tokens: number, 
/**
 * The budget it was built against.
 */
budget_tokens: number, 
/**
 * Estimated tokens in the system turn (system + persona + character +
 * memory + runtime).
 */
system_tokens: number, 
/**
 * Persona inclusion.
 */
persona: PersonaInclusion, 
/**
 * Memory items included.
 */
memory_items: number, 
/**
 * Estimated tokens of memory.
 */
memory_tokens: number, 
/**
 * History turns kept.
 */
history_turns_included: number, 
/**
 * History turns dropped to fit.
 */
history_turns_dropped: number, };
