// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quantization label as reported by the model file (e.g. a `"Q4_K_M"`- or
 * `"NF4"`-style tag). Absent for unquantized weights.
 */
export type Quant = string;
