// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A measured system-RAM reading. All values in MB.
 */
export type RamInfo = { 
/**
 * Total physical RAM.
 */
total_mb: bigint, 
/**
 * RAM available to new allocations.
 */
available_mb: bigint, };
