// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a registered model's file is actually present on disk. Computed at
 * read time (Phase 11) — **not** the same as [`ModelState`], which is runtime
 * lifecycle.
 */
export type RegistryAvailability = "Ready" | "Missing";
