// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";
import type { ModelMetadata } from "./ModelMetadata";
import type { RegistryAvailability } from "./RegistryAvailability";

/**
 * A model registry row as the frontend sees it: its [`ModelMetadata`] plus the
 * on-disk facts (Phase 11).
 */
export type RegisteredModel = { 
/**
 * Static description.
 */
metadata: ModelMetadata, 
/**
 * Absolute path to the model file (confined to the configured model dir).
 */
path: string, 
/**
 * Whether the file is present right now.
 */
availability: RegistryAvailability, 
/**
 * Devices this model can run on.
 */
devices: Array<Device>, };
