// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReservationId } from "./ReservationId";
import type { ReservationState } from "./ReservationState";
import type { ResourceKind } from "./ResourceKind";
import type { TaskId } from "./TaskId";

/**
 * One entry in the resource ledger.
 */
export type Reservation = { 
/**
 * Stable identifier.
 */
id: ReservationId, 
/**
 * Which pool.
 */
kind: ResourceKind, 
/**
 * Amount reserved, in MB.
 */
amount_mb: number, 
/**
 * The task this reservation serves, when it is tied to one.
 */
task_id: TaskId | null, 
/**
 * Current state.
 */
state: ReservationState, };
