// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a resource reservation held against the GPU / system RAM
 * ledger (Phase 13).
 */
export type ReservationId = string;
