// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a reservation. `Released` and `Denied` are terminal.
 */
export type ReservationState = "Requested" | "Held" | "Released" | "Denied";
