// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which pool a reservation draws from.
 */
export type ResourceKind = "Gpu" | "SystemRam";
