// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuMemory } from "./GpuMemory";
import type { RamInfo } from "./RamInfo";

/**
 * The resource manager's current view: last measurement + what the ledger
 * holds. `gpu` / `ram` are `None` when the hardware probe is unavailable.
 */
export type ResourceSnapshot = { 
/**
 * Last GPU measurement, if the probe works.
 */
gpu: GpuMemory | null, 
/**
 * Last system-RAM measurement, if the probe works.
 */
ram: RamInfo | null, 
/**
 * Sum of outstanding GPU reservations (committed where known, else estimate).
 */
reserved_gpu_mb: number, 
/**
 * Sum of outstanding system-RAM reservations.
 */
reserved_ram_mb: number, };
