// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource-manager tuning (schema v4). See ADR-0007.
 */
export type ResourcesConfig = { 
/**
 * VRAM (MB) held back on top of every load estimate, absorbing estimation
 * error and driver/WDDM overhead. Default 1500.
 */
vram_safety_margin_mb: number, };
