// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Location of the supervised runtime binaries (`llama-server`, later the image
 * server + Python workers). Schema v5. See ADR-0003 / ADR-0013.
 */
export type RuntimesConfig = { 
/**
 * Absolute directory holding `llama-server(.exe)` (+ its CUDA DLLs).
 * Default: `<app_data>/runtimes`. Point it into the project to keep large
 * binaries with the repo.
 */
dir: string, };
