// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sampling knobs for one generation. All optional on the wire; the adapter
 * applies backend defaults for absent fields.
 */
export type SamplingParams = { 
/**
 * Softmax temperature. `>= 0.0`; `0.0` = greedy.
 */
temperature: number | null, 
/**
 * Nucleus sampling cutoff in `0.0..=1.0`.
 */
top_p: number | null, 
/**
 * Top-k cutoff. `0` disables.
 */
top_k: number | null, 
/**
 * Hard cap on generated tokens.
 */
max_tokens: number | null, 
/**
 * Stop sequences; generation halts before emitting any of them.
 */
stop: Array<string>, 
/**
 * RNG seed for reproducibility. 32-bit to match common LLM runtimes.
 */
seed: number | null, };
