// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a generation stopped.
 */
export type StopReason = "EndOfText" | "MaxTokens" | "StopSequence" | "Cancelled" | "Error";
