// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a task is in its lifecycle. Terminal states: `Succeeded`, `Failed`,
 * `Cancelled`.
 */
export type TaskState = "Queued" | "Running" | "Succeeded" | "Failed" | "Cancelled";
