// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskId } from "./TaskId";
import type { TaskKind } from "./TaskKind";
import type { TaskState } from "./TaskState";

/**
 * A snapshot of one task. Broadcast on progress and on every state change.
 */
export type TaskStatus = { 
/**
 * The task this snapshot describes.
 */
id: TaskId, 
/**
 * What the task is doing.
 */
kind: TaskKind, 
/**
 * Lifecycle position.
 */
state: TaskState, 
/**
 * Fractional progress in `0.0..=1.0` when the task can estimate it.
 */
progress: number | null, 
/**
 * Short human-readable detail (“loading shards 3/7”, “queued behind 2”).
 */
detail: string | null, };
