// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of work a task represents.
 */
export type TaskKind = "LlmGeneration" | "ImageGeneration" | "Stt" | "Tts" | "Embedding" | "ModelDownload" | "ModelLoad" | "ModelUnload";
