// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one asynchronous task: an LLM generation, an image generation,
 * an STT/TTS/embedding job, or a model download / load / unload.
 */
export type TaskId = string;
