// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceId } from "./VoiceId";

/**
 * A stored cloned voice.
 */
export type Voice = { 
/**
 * Stable id.
 */
id: VoiceId, 
/**
 * User label (shown in the UI only).
 */
name: string, 
/**
 * `true` for the one voice the assistant currently speaks in.
 */
active: boolean, 
/**
 * RFC-3339.
 */
created_at: string, };
