// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI shows while listening (Tauri `Channel<VoiceState>`).
 */
export type VoiceState = { "kind": "Idle" } | { "kind": "Warming" } | { "kind": "Listening" } | { "kind": "Speech" } | { "kind": "Transcribing" } | { "kind": "Error" };
