// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Voice input settings (schema v6, ADR-0005). VAD thresholds stay at their
 * code defaults for v1 (edit the file to override — a nested `config_set` is a
 * later feature).
 */
export type VoiceConfig = { 
/**
 * `cpal` input device name; `null` = the system default.
 */
input_device: string | null, 
/**
 * `cpal` output device name; `null` = the system default (schema v7).
 */
output_device: string | null, 
/**
 * How long a silence must last (ms) before a spoken turn is considered
 * finished — the VAD end-of-speech hang time. Higher = more room to pause
 * between sentences before the turn is sent. `300..=5000`, default 900
 * (schema v8). Applied at the next voice session.
 */
end_of_speech_ms: number, };
