// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies an imported cloned TTS voice (Phase 19 follow-up).
 */
export type VoiceId = string;
