// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";

/**
 * The outcome carried by a [`WorkerResponse`]. Adjacently tagged:
 * `{ "status": "Ok", "body": { ... } }`. `Progress` may appear zero or more
 * times before a terminal `Ok` / `Err`.
 */
export type WorkerResult = { "status": "Ok", "body": { 
/**
 * Worker-specific result body.
 */
data: unknown, } } | { "status": "Err", "body": { 
/**
 * The failure.
 */
error: AppError, } } | { "status": "Progress", "body": { 
/**
 * Fractional progress in `0.0..=1.0`.
 */
progress: number, 
/**
 * Optional human-readable detail.
 */
detail: string | null, } };
