// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one unit of work handed to a stateless worker over stdio.
 */
export type WorkerJobId = string;
