// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which worker a message concerns.
 */
export type WorkerKind = "Stt" | "Tts" | "Embed";
