// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerKind } from "./WorkerKind";

/**
 * First line a worker emits on startup, before any job response. The supervisor
 * checks `protocol_version` against [`crate::contracts::WORKER_PROTOCOL_VERSION`]
 * and refuses a mismatch.
 */
export type WorkerHello = { 
/**
 * The protocol version the worker implements.
 */
protocol_version: number, 
/**
 * Which worker this process is.
 */
worker: WorkerKind, };
