// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the Python worker interpreter + scripts live (schema v6, ADR-0018).
 * Dev points these at `<repo>/.venv` + `<repo>/workers`; the packaged build
 * resolves siblings of the executable and ignores these.
 */
export type WorkersConfig = { 
/**
 * Absolute directory holding `stt.py`, `tts.py`, …
 */
dir: string, 
/**
 * Absolute path to the Python interpreter.
 */
python: string, };
