// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerJobId } from "./WorkerJobId";
import type { WorkerResult } from "./WorkerResult";

/**
 * A worker's reply to a [`WorkerRequest`] (one line on its stdout).
 */
export type WorkerResponse = { 
/**
 * The request this replies to.
 */
id: WorkerJobId, 
/**
 * The outcome (or a progress frame).
 */
result: WorkerResult, };
