// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerJobId } from "./WorkerJobId";
import type { WorkerKind } from "./WorkerKind";

/**
 * A unit of work sent to a worker (one line on its stdin).
 */
export type WorkerRequest = { 
/**
 * Correlates the response(s) with this request.
 */
id: WorkerJobId, 
/**
 * Target worker (a sanity check — the pipe already implies it).
 */
kind: WorkerKind, 
/**
 * Worker-specific request body; schema defined + validated by the worker's
 * phase.
 */
payload: unknown, };
