//! Typed IPC boundary between the Rust core and the React frontend.
//!
//! Design: `docs/decisions/0002-ipc-design.md`.
//! - **Commands** (`commands` module) — request/response, thin: deserialize →
//!   call a service → serialize. No business logic here.
//! - **Events** — broadcast lifecycle/state, always carrying an id where one
//!   exists. Added when a subsystem first needs to push unsolicited state
//!   (Phase 14+). Startup readiness is a *command* (`app_ready`), not an event:
//!   an event emitted during `.setup()` races the webview's subscription.
//! - **Channels** — per-request streams (tokens, progress). Added when a
//!   streaming command lands (Phase 15+).
//! - **Errors** — one boundary enum [`AppError`], mapped from per-subsystem
//!   `thiserror` enums; full chains are logged, not serialized.
//!
//! TypeScript types for every DTO/error are generated by `ts-rs` into
//! `src/bindings/` (see the `export_bindings` test). The frontend calls
//! commands through thin hand-written wrappers in `src/lib/ipc.ts`.

pub mod commands;
pub mod error;

pub use error::AppError;
