//! Typed IPC boundary between the Rust core and the React frontend.
//!
//! Design: `docs/decisions/0002-ipc-design.md`.
//! - **Commands** (`commands` module) — request/response, thin: deserialize →
//!   call a service → serialize. No business logic here.
//! - **Events** — broadcast lifecycle/state, always carrying an id where one
//!   exists.
//! - **Channels** — per-request streams (tokens, progress). Added when a
//!   streaming command lands (Phase 15+).
//! - **Errors** — one boundary enum [`AppError`], mapped from per-subsystem
//!   `thiserror` enums; full chains are logged, not serialized.
//!
//! TypeScript types for every DTO/error are generated by `ts-rs` into
//! `src/bindings/` (see the `export_bindings_*` tests). The frontend calls
//! commands through thin hand-written wrappers in `src/ipc/`.

pub mod commands;
pub mod error;

pub use error::AppError;

use serde::Serialize;
use tauri::{AppHandle, Emitter, Runtime};
use ts_rs::TS;

/// Emitted once when the core has finished setup and the UI may proceed.
pub const EVENT_APP_READY: &str = "app://ready";

/// Payload for [`EVENT_APP_READY`].
#[derive(Debug, Clone, Serialize, TS)]
#[ts(export, export_to = "../../src/bindings/")]
pub struct AppReady {
    pub version: String,
}

/// Fire the `app://ready` event.
pub fn emit_app_ready<R: Runtime>(app: &AppHandle<R>) {
    let payload = AppReady {
        version: env!("CARGO_PKG_VERSION").to_string(),
    };
    if let Err(err) = app.emit(EVENT_APP_READY, payload) {
        tracing::warn!(%err, "failed to emit app://ready");
    }
}
